#ifndef XT_RADIATOR_MONITOR_ESPCONSTANTS_H
#define XT_RADIATOR_MONITOR_ESPCONSTANTS_H

#include <ESP8266WebServer.h>

#define COMM_BAUD 115200

#define SERVER_PORT 80

#define SERVICE_WAIT 500

#define SERIAL_TIMEOUT 60000

#define NULL_CHAR 0x000
#define EOF_CHAR 0x003

#endif /*XT_RADIATOR_MONITOR_ESPCONSTANTS_H*/
